version: "3.7"

networks:
  strapi-network:
    driver: bridge
  
volumes:
  strapi-uploads:
    driver: local
  mongo-database:
    driver: local

services:
  mongodb:
    image: mongo:latest
    container_name: strapi-mongodb
    volumes:
      - mongo-database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    restart: unless-stopped
    ports:
      - 27018:27017
    networks:
      - strapi-network