version: "3"

services:
  strapi:
    image: ${BACKEND_IMAGE_NAME}
    container_name: ${BACKEND_CONTAINER_NAME}
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "1337:1337"
    volumes:
      - ./uploads:/app/public/uploads
    networks:
      - app-network

  db:
    image: mysql/mysql-server:5.7
    container_name: mysql-server
    volumes:
      - ./mysql-database:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    # ports:
    #   - 3306:3306
    networks:
      - app-network

networks:
  strapi-app-network:
    driver: bridge

# volumes:
#   mysql-database:
#       driver: local
    